services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: keyboard-base
    container_name: keyboard-base

  redis:
    image: redis:7.0.1
    container_name: keyboard-redis
    ports:
      - "6379:6379"
    restart: no

  analyzer:
    build:
      context: .
      dockerfile: Dockerfile.analyzer
    container_name: keyboard-analyzer
    volumes:
      # монтируем локальную папку ./data_output к /app/data_output
      - ./data_output:/app/data_output
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - base

  visualizer:
    build:
      context: .
      dockerfile: Dockerfile.visualizer
    container_name: keyboard-visualizer
    volumes:
      # та же папка, общая между контейнерами
      - ./data_output:/app/data_output
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      analyzer:
        condition: service_completed_successfully